---
# This role updates the Kubelet config on the cluster to set the pods per core and max pods
# It MUST be the last role to run - even after showroom etc. - because it will trigger
# a node reboot which would interfere with other workloads.

- name: Create KubeletConfig
  kubernetes.core.k8s:
    state: present
    template: kubeletconfig.yaml.j2
  register: r_kubeletconfig
  until: r_kubeletconfig is success
  retries: 20
  delay: 10
  ignore_errors: true
